### ISSUE TITLE
Play Store in app purchase no longer compatible/Unable to donate to remove ads

### ISSUE THREAD

**Issue by chasedaigle** [serso/android-calculatorpp#112]
"This app uses a billing method that is no longer supported".

**Comment by chasedaigle** [comment]
I'm on 5.0.2. I attempted to submit a bug report when the modal came up but it is unclear if it sent successfully.

**Comment by chasedaigle** [comment]
Looking through the logs it doesn't look like it sent anything to you.  So I got the email address off of the playstore and emailed a copy of the bug report and a screenshot of the issue.

**Comment by serso** [comment]
The issues is fixed in the latest version of the app - 2.1.0
