### ISSUE TITLE
88%+12% != 1

### ISSUE THREAD

**Issue by VitorVilela7** [serso/android-calculatorpp#160]
Calculator is set on advanced mode. I don't think it's a rounding issue since it's a quite obvious expression.

Picture:
![screenshot_2015-06-22-08-01-38](https://cloud.githubusercontent.com/assets/12776674/8296291/3d2c2934-1925-11e5-9c62-e4fdf5fe2428.png)

**Comment by serso** [comment]
In the world of percentages arithmetics doesn't work that easy. 88%+12% means that you get first 88% of something (1 * 0.88 = 0.88) and then add 12% of it (0.88 + 0.88 * 0.12) which is obviously not the same as 0.88 + 0.12. If you want to sum numbers first and then calculate percentage - just use brackets: (0.88+0.12)%

**Comment by VitorVilela7** [comment]
Oh I see. Oh well, I didn't know it was supposed to have such weird
behavior, but it makes sense. Thanks for clarifying it.

Please desconsider this then.
Em 23/06/2015 03:36, "Sergey Solovyev" <notifications@github.com> escreveu:
