### ISSUE TITLE
Change color schema

### ISSUE THREAD

**Issue by LeshaRB** [serso/android-calculatorpp#183]
Can you change color of add-on text
For example sin cos and other?

My father have bad vision. And he does not see these buttons. Gray color on black.

**Comment by LeshaRB** [comment]
![screenshot_2017-07-15-12-15-11-552](https://user-images.githubusercontent.com/439337/28238229-c93a5214-6957-11e7-855a-30ffae726e90.jpeg)

**Comment by serso** [comment]
There is a high-contrast option in the settings. Please try it first. It works with any theme

**Comment by LeshaRB** [comment]
Thank it's better

Close issue
