### ISSUE TITLE
Multiplication bug

### ISSUE THREAD

**Issue by emmanuelantony2000** [serso/android-calculatorpp#185]
![screenshot_20170727-193337](https://user-images.githubusercontent.com/19288251/28674322-b79d412e-7302-11e7-854c-99578d68686c.png)
Dividing 22.4 by 0.224 gives 99.99999999999999 instead of giving 100 as the answer.

**Comment by serso** [comment]
Please change the precision of the number format in the settings. In the latest version 2.2.6 the default value for ENG mode is 10
