### ISSUE TITLE
Disable Autofill Framework (Oreo) integration

### ISSUE THREAD

**Issue by thousandsofthem** [serso/android-calculatorpp#191]
At this moment calculator is showing autofill framework popup (fill password with ...), introduced in Android 8.0 Oreo
![screenshot_20180305-210037_calculator](https://user-images.githubusercontent.com/736279/38767924-b6075a52-3ff3-11e8-85c4-a96ced569161.jpg)

**Comment by ccoenen** [comment]
I think this can be closed, It used to happen to me, but now the problem is gone.
