### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [serso/android-calculatorpp#205]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by Korb** [comment]
Still no screenshots at https://f-droid.org/packages/org.solovyev.android.calculator/
![Screenshot_2023_0613_175039_org fdroid fdroid](https://github.com/serso/android-calculatorpp/assets/3509797/5a820cb8-889a-435a-b0ca-8ad5669e8dec)
