### ISSUE TITLE
Overlap with the Android status bar.

### ISSUE THREAD

**Issue by alopecoid** [serso/android-calculatorpp#230]
Hi,

Starting recently, I believe with version 2.3.4 (released on Oct 5, 2024), the app started to overlap with the Android status bar and also as a result prevent menu accessibility due to the phone's rounded edges. This is best explained in a photo of my phone (see below). Also note that I use the smallest font/display sizes in system settings.

![calc_issue](https://github.com/user-attachments/assets/5c368056-2771-45f4-bbb5-3236ca471d2f)

Thank you.

Calculator ++ 2.3.4
Android 15 (Build AP3A.241005.015)
Google Pixel 9 Pro

**Comment by serso** [comment]
I cannot reproduce the issue. This is how the app looks like to me on an emulator with a cutout enabled:
![image](https://github.com/user-attachments/assets/84d11600-c49e-43cf-92a8-b91357fb6913)

**Comment by serso** [comment]
I see, the issue only affects API 35 devices: https://developer.android.com/about/versions/15/behavior-changes-15#edge-to-edge
Will take a look soon.

**Comment by alopecoid** [comment]
Verified that the fix seems to be working; Calculator ++ 2.3.5 no longer exhibits the above behavior.
Awesome, thank you!
